#include "stdafx.h"

#pragma comment(lib, "netapi32.lib")
#pragma comment(lib, "wsock32.lib")
#pragma comment(lib, "Htmlhelp.lib")

#pragma comment(lib, "SetupApi.lib")
#pragma comment(lib, "Iphlpapi.lib")
#pragma comment(lib, "Wbemuuid.lib")

#if 0
#pragma comment(lib, "ofstd.lib")
#pragma comment(lib, "oflog.lib")
#pragma comment(lib, "dcmdata.lib")
#pragma comment(lib, "dcmimgle.lib")
#pragma comment(lib, "dcmimage.lib")
#pragma comment(lib, "ijg8.lib")
#pragma comment(lib, "ijg12.lib")
#pragma comment(lib, "ijg16.lib")
#pragma comment(lib, "dcmjpeg.lib")
#pragma comment(lib, "dcmnet.lib")
#pragma comment(lib, "dcmdsig.lib")
#pragma comment(lib, "dcmsr.lib")
#pragma comment(lib, "dcmtls.lib")
#pragma comment(lib, "dcmpstat.lib")
#pragma comment(lib, "dcmwlm.lib")
#pragma comment(lib, "dcmqrdb.lib")
#pragma comment(lib, "dcmtkeay.lib")
#pragma comment(lib, "dcmtkssl.lib")
#pragma comment(lib, "iconv.lib")
#pragma comment(lib, "libtiff.lib")
#pragma comment(lib, "libpng.lib")
#pragma comment(lib, "libxml2.lib")
#pragma comment(lib, "zlib.lib")
#endif
