/*******************************************************************
Autor:         Jinfeng Chen
E-mail:        jinfengcc@gmail.com
Date:          09-29-2013
Description:   Create a dialog for technicians for tracey machine alignment.
This Dialog will be generated by clicking 'camera alignment button inside the 'ctrl+q' interface.

*****************************************************************************************/

//***************************************************************************************

#pragma once

//***************************************************************************************

#include "WFVrfTestWnd.h"

//***************************************************************************************

class CWFVrfTestDlg : public CDialog
{
public:

	CWFVrfTestDlg(CWnd* pParentWnd, CWFExam* pWFExam);

private:

	int m_w;
	int m_h;

	CButton m_ReWfExamBtn;
	CButton m_CancelBtn;

	CWFExam* m_pWFExam;

	CWFVrfTestWnd* m_pSumWnd;

	void ShowVefWnd();

	HACCEL  m_hAccel;

	virtual BOOL PreTranslateMessage(MSG* pMsg) override;

	virtual void OnCancel() override;
	virtual void DoDataExchange(CDataExchange* pDX) override;
	BOOL OnInitDialog();

	afx_msg void OnReExamBtnClicked();

	DECLARE_MESSAGE_MAP()
};

//***************************************************************************************
