//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceyRzdcxActivation.RZDCX {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RZDCX.ActivationWSSoap")]
    public interface ActivationWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        System.Threading.Tasks.Task testAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LegacyActivation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraceyRzdcxActivation.RZDCX.LegacyActivationResponse LegacyActivation(TraceyRzdcxActivation.RZDCX.LegacyActivationRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LegacyActivation", ReplyAction="*")]
        System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.LegacyActivationResponse> LegacyActivationAsync(TraceyRzdcxActivation.RZDCX.LegacyActivationRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Activate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraceyRzdcxActivation.RZDCX.ActivationResponse Activate(TraceyRzdcxActivation.RZDCX.ActivationRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Activate", ReplyAction="*")]
        System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.ActivationResponse> ActivateAsync(TraceyRzdcxActivation.RZDCX.ActivationRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivateWithLegacy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraceyRzdcxActivation.RZDCX.ActivationWithLegacyResponse ActivateWithLegacy(TraceyRzdcxActivation.RZDCX.ActivationWithLegacyRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivateWithLegacy", ReplyAction="*")]
        System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.ActivationWithLegacyResponse> ActivateWithLegacyAsync(TraceyRzdcxActivation.RZDCX.ActivationWithLegacyRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivateEvaluationLicense", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActivateEvaluationLicense(string ActivationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivateEvaluationLicense", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ActivateEvaluationLicenseAsync(string ActivationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EvaluateWithLegacy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraceyRzdcxActivation.RZDCX.ActivationResponse EvaluateWithLegacy(TraceyRzdcxActivation.RZDCX.EvaluationWithLegacyRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EvaluateWithLegacy", ReplyAction="*")]
        System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.ActivationResponse> EvaluateWithLegacyAsync(TraceyRzdcxActivation.RZDCX.EvaluationWithLegacyRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Evaluate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraceyRzdcxActivation.RZDCX.ActivationResponse Evaluate(TraceyRzdcxActivation.RZDCX.EvaluationRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Evaluate", ReplyAction="*")]
        System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.ActivationResponse> EvaluateAsync(TraceyRzdcxActivation.RZDCX.EvaluationRequest input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TraceyRzdcxActivation.RZDCX.GetCreditResponse GetCredit(TraceyRzdcxActivation.RZDCX.GetCreditRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.GetCreditResponse> GetCreditAsync(TraceyRzdcxActivation.RZDCX.GetCreditRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LegacyActivationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Product productCodeField;
        
        private PurchaseInfo purchaseInfoField;
        
        private string licenseRequestFileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Product ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PurchaseInfo PurchaseInfo {
            get {
                return this.purchaseInfoField;
            }
            set {
                this.purchaseInfoField = value;
                this.RaisePropertyChanged("PurchaseInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LicenseRequestFileContent {
            get {
                return this.licenseRequestFileContentField;
            }
            set {
                this.licenseRequestFileContentField = value;
                this.RaisePropertyChanged("LicenseRequestFileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Product {
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        RZDCX,
        
        /// <remarks/>
        DSRSVC,
        
        /// <remarks/>
        DICOMIZER,
        
        /// <remarks/>
        HL7Kit,
        
        /// <remarks/>
        HRZSDK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchaseInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerEmailField;
        
        private string serialNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerEmail {
            get {
                return this.customerEmailField;
            }
            set {
                this.customerEmailField = value;
                this.RaisePropertyChanged("CustomerEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Product productCodeField;
        
        private string emailField;
        
        private string nameField;
        
        private string companyField;
        
        private string phoneField;
        
        private string registrationCodeField;
        
        private string iPAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Product ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RegistrationCode {
            get {
                return this.registrationCodeField;
            }
            set {
                this.registrationCodeField = value;
                this.RaisePropertyChanged("RegistrationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
                this.RaisePropertyChanged("IPAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluationWithLegacyRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Product productCodeField;
        
        private string emailField;
        
        private string nameField;
        
        private string companyField;
        
        private string phoneField;
        
        private string registrationCodeField;
        
        private string iPAddressField;
        
        private string licenseRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Product ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RegistrationCode {
            get {
                return this.registrationCodeField;
            }
            set {
                this.registrationCodeField = value;
                this.RaisePropertyChanged("RegistrationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
                this.RaisePropertyChanged("IPAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LicenseRequest {
            get {
                return this.licenseRequestField;
            }
            set {
                this.licenseRequestField = value;
                this.RaisePropertyChanged("LicenseRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivationWithLegacyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ActivationResultCode statusField;
        
        private string statusDescriptionField;
        
        private string activationCodeField;
        
        private System.DateTime expirationDateField;
        
        private string licenseContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ActivationResultCode Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ActivationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
                this.RaisePropertyChanged("ActivationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LicenseContent {
            get {
                return this.licenseContentField;
            }
            set {
                this.licenseContentField = value;
                this.RaisePropertyChanged("LicenseContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ActivationResultCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        NotFoundInDB,
        
        /// <remarks/>
        InvalidRegistrationCode,
        
        /// <remarks/>
        TooMany,
        
        /// <remarks/>
        Expired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivationWithLegacyRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Product productCodeField;
        
        private PurchaseInfo purchaseInfoField;
        
        private string registrationCodeField;
        
        private string licenseRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Product ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PurchaseInfo PurchaseInfo {
            get {
                return this.purchaseInfoField;
            }
            set {
                this.purchaseInfoField = value;
                this.RaisePropertyChanged("PurchaseInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegistrationCode {
            get {
                return this.registrationCodeField;
            }
            set {
                this.registrationCodeField = value;
                this.RaisePropertyChanged("RegistrationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LicenseRequest {
            get {
                return this.licenseRequestField;
            }
            set {
                this.licenseRequestField = value;
                this.RaisePropertyChanged("LicenseRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ActivationResultCode statusField;
        
        private string statusDescriptionField;
        
        private string activationCodeField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ActivationResultCode Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ActivationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
                this.RaisePropertyChanged("ActivationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActivationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Product productCodeField;
        
        private PurchaseInfo purchaseInfoField;
        
        private string registrationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Product ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PurchaseInfo PurchaseInfo {
            get {
                return this.purchaseInfoField;
            }
            set {
                this.purchaseInfoField = value;
                this.RaisePropertyChanged("PurchaseInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegistrationCode {
            get {
                return this.registrationCodeField;
            }
            set {
                this.registrationCodeField = value;
                this.RaisePropertyChanged("RegistrationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LegacyActivationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ActivationResultCode statusField;
        
        private string statusDescriptionField;
        
        private string licenseFileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ActivationResultCode Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LicenseFileContent {
            get {
                return this.licenseFileContentField;
            }
            set {
                this.licenseFileContentField = value;
                this.RaisePropertyChanged("LicenseFileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCredit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TraceyRzdcxActivation.RZDCX.LegacyActivationRequest purchData;
        
        public GetCreditRequest() {
        }
        
        public GetCreditRequest(TraceyRzdcxActivation.RZDCX.LegacyActivationRequest purchData) {
            this.purchData = purchData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCreditResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetCreditResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int UnitNum;
        
        public GetCreditResponse() {
        }
        
        public GetCreditResponse(int GetCreditResult, int UnitNum) {
            this.GetCreditResult = GetCreditResult;
            this.UnitNum = UnitNum;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActivationWSSoapChannel : TraceyRzdcxActivation.RZDCX.ActivationWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivationWSSoapClient : System.ServiceModel.ClientBase<TraceyRzdcxActivation.RZDCX.ActivationWSSoap>, TraceyRzdcxActivation.RZDCX.ActivationWSSoap {
        
        public ActivationWSSoapClient() {
        }
        
        public ActivationWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivationWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivationWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivationWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void test() {
            base.Channel.test();
        }
        
        public System.Threading.Tasks.Task testAsync() {
            return base.Channel.testAsync();
        }
        
        public TraceyRzdcxActivation.RZDCX.LegacyActivationResponse LegacyActivation(TraceyRzdcxActivation.RZDCX.LegacyActivationRequest input) {
            return base.Channel.LegacyActivation(input);
        }
        
        public System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.LegacyActivationResponse> LegacyActivationAsync(TraceyRzdcxActivation.RZDCX.LegacyActivationRequest input) {
            return base.Channel.LegacyActivationAsync(input);
        }
        
        public TraceyRzdcxActivation.RZDCX.ActivationResponse Activate(TraceyRzdcxActivation.RZDCX.ActivationRequest input) {
            return base.Channel.Activate(input);
        }
        
        public System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.ActivationResponse> ActivateAsync(TraceyRzdcxActivation.RZDCX.ActivationRequest input) {
            return base.Channel.ActivateAsync(input);
        }
        
        public TraceyRzdcxActivation.RZDCX.ActivationWithLegacyResponse ActivateWithLegacy(TraceyRzdcxActivation.RZDCX.ActivationWithLegacyRequest input) {
            return base.Channel.ActivateWithLegacy(input);
        }
        
        public System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.ActivationWithLegacyResponse> ActivateWithLegacyAsync(TraceyRzdcxActivation.RZDCX.ActivationWithLegacyRequest input) {
            return base.Channel.ActivateWithLegacyAsync(input);
        }
        
        public string ActivateEvaluationLicense(string ActivationCode) {
            return base.Channel.ActivateEvaluationLicense(ActivationCode);
        }
        
        public System.Threading.Tasks.Task<string> ActivateEvaluationLicenseAsync(string ActivationCode) {
            return base.Channel.ActivateEvaluationLicenseAsync(ActivationCode);
        }
        
        public TraceyRzdcxActivation.RZDCX.ActivationResponse EvaluateWithLegacy(TraceyRzdcxActivation.RZDCX.EvaluationWithLegacyRequest input) {
            return base.Channel.EvaluateWithLegacy(input);
        }
        
        public System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.ActivationResponse> EvaluateWithLegacyAsync(TraceyRzdcxActivation.RZDCX.EvaluationWithLegacyRequest input) {
            return base.Channel.EvaluateWithLegacyAsync(input);
        }
        
        public TraceyRzdcxActivation.RZDCX.ActivationResponse Evaluate(TraceyRzdcxActivation.RZDCX.EvaluationRequest input) {
            return base.Channel.Evaluate(input);
        }
        
        public System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.ActivationResponse> EvaluateAsync(TraceyRzdcxActivation.RZDCX.EvaluationRequest input) {
            return base.Channel.EvaluateAsync(input);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TraceyRzdcxActivation.RZDCX.GetCreditResponse TraceyRzdcxActivation.RZDCX.ActivationWSSoap.GetCredit(TraceyRzdcxActivation.RZDCX.GetCreditRequest request) {
            return base.Channel.GetCredit(request);
        }
        
        public int GetCredit(TraceyRzdcxActivation.RZDCX.LegacyActivationRequest purchData, out int UnitNum) {
            TraceyRzdcxActivation.RZDCX.GetCreditRequest inValue = new TraceyRzdcxActivation.RZDCX.GetCreditRequest();
            inValue.purchData = purchData;
            TraceyRzdcxActivation.RZDCX.GetCreditResponse retVal = ((TraceyRzdcxActivation.RZDCX.ActivationWSSoap)(this)).GetCredit(inValue);
            UnitNum = retVal.UnitNum;
            return retVal.GetCreditResult;
        }
        
        public System.Threading.Tasks.Task<TraceyRzdcxActivation.RZDCX.GetCreditResponse> GetCreditAsync(TraceyRzdcxActivation.RZDCX.GetCreditRequest request) {
            return base.Channel.GetCreditAsync(request);
        }
    }
}
